### ISSUE TITLE
Does the babel-plugin automatically convert the sx prop to styles? 

### ISSUE THREAD

**Issue by cmaycumber** [intergalacticspacehighway/react-native-styled-variants#2]
This library seems pretty sweet. After taking a quick look at the example; I see that the default `View` exported from react-native has an sx prop passed? Just out of curiosity are you using a custom jsx runtime like `theme-ui` or are you babel to apply the styles?

**Comment by intergalacticspacehighway** [comment]
@cmaycumber Thanks! 
Yes, `sx` prop is transformed to stylesheet or style object during build time using babel plugin.
I just pushed some documentation and a playground where you can see how it works. Would love to hear your thoughts! :)

Documentation - https://styled-variants.vercel.app/
Playground - https://styled-variants.vercel.app/playground/
